runtime: nodejs18

env_variables:
  MONGO_URI=mongodb+srv://202152323:202152323@cluster0.5tlo1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  SECRET_KEY=secret
  EMAIL=shubham26.test@gmail.com
  PASSWORD=yfff corm kbfi pigp
  GOOGLE_CLIENT_ID=480470105503-i5nrtdqooldd9gdd1ks6h55vg9g7p1qq.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET=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
  RECAPTCHA_SECRET=6LcXQ0kqAAAAABs4y5qi8_I9ldO7f4CrDqNbYK3c
  FRONTEND_URL=https://ecommerce-frontend-two-nu.vercel.app
  PAYPAL_CLIENT_ID=AfaMs_NOtTipJw6SA0ciqIRw19qqFGxYQRVkQkvk9NLzAmzX2rFsWl4cns5aTifjtE-fSPjps1qwQaVd
  PAYPAL_CLIENT_SECRET=ENf5jgEkxg9cmhaj9xyzjaZmRLURPwz09pS8vzWbX5AeBwZl6IiF5tpkg22uuMFE6lvAQUDeHsEQTZCY

